### PR TITLE
PCF-81 eggd rnaseqc v1.0.0 - add HGNC ID & symbol

### PR DESCRIPTION
**Pull request by Aisha-D**
The coverage metrics file outputs ENSG, which can be converted to HGNC ID and symbol with the use of the HGNC static file. The new coverage metrics with annotation is also outputted

Job with the applet with new changes: https://platform.dnanexus.com/projects/GQ9fjy043p6vV3990Kf3Z70z/monitor/job/GQK38B843p6g8zBJgF7f1Xyb

Job with the applet previously: https://platform.dnanexus.com/projects/GQ9fjy043p6vV3990Kf3Z70z/monitor/job/GQGpqX843p6zxgjvxb9qV7Vf

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/2)

### CODE REVIEW

**Review by corbin-chris — CHANGES_REQUESTED** [review]
Make sure to add the new output file to your list of outputs in the README :) 
Please see information about keeping ENSG versioning in the final output file. Otherwise good.

> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/2#-:-NRIA06757kS_THr0KiD:b-xmm3i4)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @Aisha-D)

___
*[`dxapp.json` line 58 at r1](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/2#-NRI6NtvBeTiTEgLFi2N:-NRI6NtvBeTiTEgLFi2O:b6ynnsm) ([raw file](https://github.com/eastgenomics/eggd_RNASeQC/blob/76234443b48a9517729f75e563ac752ca2e9c0ea/dxapp.json#L58)):*
> ```JSON
>         "*.txt"
>       ],
>       "help": "HGNC complete static file, tab-separated"
> ```

BTW give info on original download source https://www.genenames.org/download/archive/ 
___
*[`resources/home/dnanexus/hgnc_annotation.py` line 6 at r1](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/2#-NRI7UG805HBxxEjj4RD:-NRI7UG805HBxxEjj4RE:bz65c4e) ([raw file](https://github.com/eastgenomics/eggd_RNASeQC/blob/76234443b48a9517729f75e563ac752ca2e9c0ea/resources/home/dnanexus/hgnc_annotation.py#L6)):*
> ```Python
> 
> def parse_args():
>     """Parse through arguements
> ```

BTW *arguments

'args: Variable that you can extract relevant arguements inputs needed' - bit unclear, maybe 'Variable that you can extract relevant arguments from. Inputs needed'
___
*[`resources/home/dnanexus/hgnc_annotation.py` line 38 at r1](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/2#-NRI8DZ5ETmfiH0Dhl58:-NRI8DZ5ETmfiH0Dhl59:b2ovdrj) ([raw file](https://github.com/eastgenomics/eggd_RNASeQC/blob/76234443b48a9517729f75e563ac752ca2e9c0ea/resources/home/dnanexus/hgnc_annotation.py#L38)):*
> ```Python
>     dat = pd.read_csv(args.cov_metrics_file, sep = "\t")
>     # remove ensembl gene versions
>     dat['gene_id'] = dat['gene_id'].str.split('.').str[0]
> ```

Is it possible to please leave the ENSG versions in the final output file? Seems a shame to throw out version data when we have it. If you want to keep everything Pandas, maybe:
- make a new column, called something 'gene_id_versionless', which is made through the same '.' splitting you currently do directly on 'gene_id'
- use 'gene_id_versionless' to find your HGNCs
- drop 'gene_id_versionless' before you write the final file out
- add a note to the documentation to clarify that HGNCs are looked up based on versionless ENSGs - so it's obvious

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/2)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @corbin-chris)

___
*[`resources/home/dnanexus/hgnc_annotation.py` line 38 at r1](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/2#-NRI8DZ5ETmfiH0Dhl58:-NRIkJBN4AqXhlsOJPfS:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_RNASeQC/blob/76234443b48a9517729f75e563ac752ca2e9c0ea/resources/home/dnanexus/hgnc_annotation.py#L38)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Is it possible to please leave the ENSG versions in the final output file? Seems a shame to throw out version data when we have it. If you want to keep everything Pandas, maybe:
- make a new column, called something 'gene_id_versionless', which is made through the same '.' splitting you currently do directly on 'gene_id'
- use 'gene_id_versionless' to find your HGNCs
- drop 'gene_id_versionless' before you write the final file out
- add a note to the documentation to clarify that HGNCs are looked up based on versionless ENSGs - so it's obvious
</blockquote></details>

Done.

**Review by Aisha-D — COMMENTED** [review]
the job output with the changes are here: https://platform.dnanexus.com/projects/GQ9fjy043p6vV3990Kf3Z70z/monitor/job/GQKp45843p6z72gjkB1gJ1b2

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/2#-:-NRJ3lr63RZqtZU62qfy:b-sf3wu3)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @corbin-chris)

**Review by corbin-chris — APPROVED** [review]
Looks good!

> Reviewed 1 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/2#-:-NRJ4LhT1VHrzW820kT0:b-vs1prh)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Aisha-D)

**Pull request merged**
