### PR TITLE
PCF-129 eggd rnaseqc v1.1.0

### PR DESCRIPTION
**Pull request by Aisha-D**
Changes:
- use CTAT bundle to get the gtf file and collapse it to be used by RNA-SeQC
- remove use of hgnc text file for annotating ENSG and use the gtf file instead

Job: https://platform.dnanexus.com/projects/GQ9fjy043p6vV3990Kf3Z70z/monitor/job/GYP2Xy843p6Zff7FQk696GP0

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/4)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/4)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @Aisha-D)

___
*[`resources/home/dnanexus/hgnc_annotation.py` line 40 at r1](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/4#-NembqsV60mDhbGb56u2:-NembqsV60mDhbGb56u3:b-udztr3) ([raw file](https://github.com/eastgenomics/eggd_RNASeQC/blob/9aae20fb0d3f0c2318b50023e145a5252b20f451/resources/home/dnanexus/hgnc_annotation.py#L40)):*
> ```Python
>     # load hgnc file
>     ref_flat = pd.read_csv(args.gtf_file, sep = "\t", skiprows = 5,
>                             names=['chr', 'source', 'feature', 'start','end', 'score', 'strand', 'frame','attribute'], header=None)
> ```

line length, consider something like this for reading goodness

```
ref_flat = pd.read_csv(
    args.gtf_file,
    sep = "\t",
    skiprows = 5,
    header=None,
    names=[
        'chr', 'source', 'feature', 'start','end',
        'score', 'strand', 'frame','attribute'
    ]
)

```



_Code quote:_
```Python
    ref_flat = pd.read_csv(args.gtf_file, sep = "\t", skiprows = 5,
                            names=['chr', 'source', 'feature', 'start','end', 'score', 'strand', 'frame','attribute'], header=None)
```
___
*[`resources/home/dnanexus/hgnc_annotation.py` line 44 at r1](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/4#-NemcMvqAcx3xFhylACZ:-NemcMvqAcx3xFhylAC_:b7k2kx) ([raw file](https://github.com/eastgenomics/eggd_RNASeQC/blob/9aae20fb0d3f0c2318b50023e145a5252b20f451/resources/home/dnanexus/hgnc_annotation.py#L44)):*
> ```Python
>     ref_flat = ref_flat[ref_flat['feature'] == "gene"]
> 
>     ref_flat2 = pd.concat([ref_flat, ref_flat['attribute'].str.split('; ', expand=True)], axis=1).drop(
> ```

so longggg

```
ref_flat2 = pd.concat(
    [ref_flat, ref_flat['attribute'].str.split('; ', expand=True)], axis=1
).drop('attribute', axis=1)

```
___
*[`resources/home/dnanexus/hgnc_annotation.py` line 47 at r1](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/4#-Nemcnhu9Lz88NQEIVxq:-NemcnhvEatUnr27Qh4V:b-iheq0k) ([raw file](https://github.com/eastgenomics/eggd_RNASeQC/blob/9aae20fb0d3f0c2318b50023e145a5252b20f451/resources/home/dnanexus/hgnc_annotation.py#L47)):*
> ```Python
>         'attribute', axis=1
>     )
>     ref_flat2 = ref_flat2.iloc[:, [5,7,9]]
> ```

confused what this is doing, are you just selecting columns? can you add some example of the data structure for understandabilityness for my brain please and thankyou



_Code quote:_
```Python
ref_flat2 = ref_flat2.iloc[:, [5,7,9]]
```
___
*[`resources/home/dnanexus/hgnc_annotation.py` line 68 at r1](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/4#-Nemd0Y26DgE6bwTCF3B:-Nemd0Y3Bt3F55HDCRAP:b-j97yko) ([raw file](https://github.com/eastgenomics/eggd_RNASeQC/blob/9aae20fb0d3f0c2318b50023e145a5252b20f451/resources/home/dnanexus/hgnc_annotation.py#L68)):*
> ```Python
>     dat_merged = dat_merged[['hgnc_symbol', 'hgnc_id','gene_id',
>                 'coverage_mean', 'coverage_std', 'coverage_CV']]
>     dat_merged.rename(columns = {'gene_id':'ENSG_id','hgnc_symbol':'HGNC_symbol', 'hgnc_id':'HGNC_id'}, inplace = True)
> ```

length again, also splitting in some way makes it more readable I think:
```
dat_merged.rename(
    columns = {
        'gene_id':'ENSG_id',
        'hgnc_symbol':'HGNC_symbol',
        'hgnc_id':'HGNC_id'
    }, inplace = True
)
```
but also if you define the column names above, why not just make them these directly? (also can id be ID pls)
___
*[`src/eggd_RNASeQC.sh` line 27 at r1](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/4#-NemdcOoDvumtmYyKOFd:-NemdcOpEaiEWNLqXeW2:b-m1en3x) ([raw file](https://github.com/eastgenomics/eggd_RNASeQC/blob/9aae20fb0d3f0c2318b50023e145a5252b20f451/src/eggd_RNASeQC.sh#L27)):*
> ```Shell
> 
>     echo "---------- Decompress CTAT bundle -------------"
>     tar zxvf ${CTAT_bundle_path##*/}
> ```

is this the thing we were talking about only needing to extract one file from?



_Code quote:_
```Shell
 tar zxvf ${CTAT_bundle_path##*/}
```

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/4)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @jethror1)

___
*[`resources/home/dnanexus/hgnc_annotation.py` line 40 at r1](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/4#-NembqsV60mDhbGb56u2:-NewPCTYECtTgmEtmFu9:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_RNASeQC/blob/9aae20fb0d3f0c2318b50023e145a5252b20f451/resources/home/dnanexus/hgnc_annotation.py#L40)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

line length, consider something like this for reading goodness

```
ref_flat = pd.read_csv(
    args.gtf_file,
    sep = "\t",
    skiprows = 5,
    header=None,
    names=[
        'chr', 'source', 'feature', 'start','end',
        'score', 'strand', 'frame','attribute'
    ]
)

```
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/hgnc_annotation.py` line 44 at r1](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/4#-NemcMvqAcx3xFhylACZ:-NewPCle2AtSgOPMZCDy:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_RNASeQC/blob/9aae20fb0d3f0c2318b50023e145a5252b20f451/resources/home/dnanexus/hgnc_annotation.py#L44)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

so longggg

```
ref_flat2 = pd.concat(
    [ref_flat, ref_flat['attribute'].str.split('; ', expand=True)], axis=1
).drop('attribute', axis=1)

```
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/hgnc_annotation.py` line 47 at r1](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/4#-Nemcnhu9Lz88NQEIVxq:-NewPDAxDYvuo-Bu-IbI:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_RNASeQC/blob/9aae20fb0d3f0c2318b50023e145a5252b20f451/resources/home/dnanexus/hgnc_annotation.py#L47)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

confused what this is doing, are you just selecting columns? can you add some example of the data structure for understandabilityness for my brain please and thankyou
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/hgnc_annotation.py` line 68 at r1](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/4#-Nemd0Y26DgE6bwTCF3B:-NewPDgNDEhGCWIzWc-v:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_RNASeQC/blob/9aae20fb0d3f0c2318b50023e145a5252b20f451/resources/home/dnanexus/hgnc_annotation.py#L68)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

length again, also splitting in some way makes it more readable I think:
```
dat_merged.rename(
    columns = {
        'gene_id':'ENSG_id',
        'hgnc_symbol':'HGNC_symbol',
        'hgnc_id':'HGNC_id'
    }, inplace = True
)
```
but also if you define the column names above, why not just make them these directly? (also can id be ID pls)
</blockquote></details>

Done.

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/4)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @jethror1)

___
*[`src/eggd_RNASeQC.sh` line 27 at r1](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/4#-NemdcOoDvumtmYyKOFd:-NewRhIVD1ZxsL6_xdKu:bc8av6r) ([raw file](https://github.com/eastgenomics/eggd_RNASeQC/blob/9aae20fb0d3f0c2318b50023e145a5252b20f451/src/eggd_RNASeQC.sh#L27)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

is this the thing we were talking about only needing to extract one file from?
</blockquote></details>

will deal with in next PR

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/4)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @Aisha-D)

___
*[`resources/home/dnanexus/hgnc_annotation.py` line 80 at r3](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/4#-NewxIXuCetZbzqRl8S6:-NewxIXuCetZbzqRl8S7:b-811ym3) ([raw file](https://github.com/eastgenomics/eggd_RNASeQC/blob/59627000b1d3feaa0c20e1f28b30a97ca6c428b7/resources/home/dnanexus/hgnc_annotation.py#L80)):*
each of these can be reduced down to one-line if you just want to get the text between the double quotes:
```
>>> df
                       ENSG_ID         hgnc_symbol               HGNC_ID
0  gene_id "ENSG00000223972.5"  hgnc_symbol "BRAF"  hgnc_id "HGNC:37102"

>>> df['ENSG_ID'].str.extract('"(.*?)"')
                   0
0  ENSG00000223972.5
```



_Code quote:_
```Python
    ref_flat2['ENSG_ID'] = ref_flat2['ENSG_ID'].str.split('gene_id').str[1]
    ref_flat2['ENSG_ID'] = ref_flat2['ENSG_ID'].str.replace(r'"', '', regex=True)
    ref_flat2['hgnc_symbol'] = ref_flat2['hgnc_symbol'].str.split('gene_name').str[1]
    ref_flat2['hgnc_symbol'] = ref_flat2['hgnc_symbol'].str.replace(r'"', '', regex=True)
    ref_flat2['HGNC_ID'] = ref_flat2['HGNC_ID'].str.split('hgnc_id').str[1]
    ref_flat2['HGNC_ID'] = ref_flat2['HGNC_ID'].str.replace(r'"', '', regex=True)
    ref_flat2['HGNC_ID'] = ref_flat2['HGNC_ID'].str.replace(r';', '', regex=True)

    #remove ws
    ref_flat2['ENSG_ID'] = ref_flat2['ENSG_ID'].str.strip()
    ref_flat2['hgnc_symbol'] = ref_flat2['hgnc_symbol'].str.strip()
    ref_flat2['HGNC_ID'] = ref_flat2['HGNC_ID'].str.strip()
```

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 2 files at r5, 2 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/4)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @Aisha-D)

**Review by jethror1 — COMMENTED** [review]
> Reviewed 1 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/4)* status: all files reviewed, 1 unresolved discussion (waiting on @Aisha-D)

**Pull request merged**
