### PR TITLE
PCF-81 eggd_RNAseQC v1.0.0 - first PR

### PR DESCRIPTION
**Pull request by Aisha-D**
First version of applet to allow QCing of RNA bam files

Job with coverage set as false: https://platform.dnanexus.com/projects/GQ9fjy043p6vV3990Kf3Z70z/monitor/job/GQB7Yq843p6Vv5GjxB00xqGq

Job with coverage set as true:
https://platform.dnanexus.com/projects/GQ9fjy043p6vV3990Kf3Z70z/monitor/job/GQB844j43p6p6Z5fQvx95J18

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/1)

### CODE REVIEW

**Review by Yu-jinKim — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/1)* status: all files reviewed, 2 unresolved discussions (waiting on @Aisha-D)

___
*[`dxapp.json` line 15 at r2](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/1#-NQkMfHMDdCHzLnasMjB:-NQkMfHMDdCHzLnasMjC:bqjhmfr) ([raw file](https://github.com/eastgenomics/eggd_RNASeQC/blob/02e80febc03ad699e36ba347e062d1812e8bbc1b/dxapp.json#L15)):*
> ```JSON
>         "*"
>       ],
>       "help": ""
> ```

can we get some documentation on the inputs and the outputs?
___
*[`src/eggd_RNASeQC.sh` line 25 at r2](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/1#-NQkNjjlCIu001KMeJr8:-NQkNjjlCIu001KMeJr9:b9044f6) ([raw file](https://github.com/eastgenomics/eggd_RNASeQC/blob/02e80febc03ad699e36ba347e062d1812e8bbc1b/src/eggd_RNASeQC.sh#L25)):*
> ```Shell
>     # Run RNASeQ command depending on whether coverage is set
>     if [ "$coverage" == 'true' ]; then
>         docker run  -v /home/dnanexus/:/data ${IMAGE_ID} /bin/bash -c \
> ```

i think you could build the docker cmd before adding the `--coverage` option in the if/else i.e.
```
docker_cmd="docker run -v /home/dnanexus/:/data ${IMAGE_ID} /bin/bash -c "cd /data ; rnaseqc $gtf $bam --bed $bed

if [ "$coverage" == 'true' ]; then
    docker_cmd+=" --coverage"
fi

docker_cmd+=" out/rnaseqc_out"
```

smarter examples here: https://github.com/eastgenomics/eggd_athena/blob/main/src/eggd_athena.sh#L85

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/1)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @Yu-jinKim)

___
*[`dxapp.json` line 15 at r2](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/1#-NQkMfHMDdCHzLnasMjB:-NR327k99_opTpsRcNWQ:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_RNASeQC/blob/02e80febc03ad699e36ba347e062d1812e8bbc1b/dxapp.json#L15)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

can we get some documentation on the inputs and the outputs?
</blockquote></details>

Done.
___
*[`src/eggd_RNASeQC.sh` line 25 at r2](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/1#-NQkNjjlCIu001KMeJr8:-NR328bR9hEpDnMjnPPq:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_RNASeQC/blob/02e80febc03ad699e36ba347e062d1812e8bbc1b/src/eggd_RNASeQC.sh#L25)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

i think you could build the docker cmd before adding the `--coverage` option in the if/else i.e.
```
docker_cmd="docker run -v /home/dnanexus/:/data ${IMAGE_ID} /bin/bash -c "cd /data ; rnaseqc $gtf $bam --bed $bed

if [ "$coverage" == 'true' ]; then
    docker_cmd+=" --coverage"
fi

docker_cmd+=" out/rnaseqc_out"
```

smarter examples here: https://github.com/eastgenomics/eggd_athena/blob/main/src/eggd_athena.sh#L85
</blockquote></details>

Done.

**Review by Yu-jinKim — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/1)* status: all files reviewed, 1 unresolved discussion (waiting on @Aisha-D)

___
*[`dxapp.json` line 24 at r3](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/1#-NR3TX7TAL7jWHK3Lm7c:-NR3TX7TAL7jWHK3Lm7d:bfsorc6) ([raw file](https://github.com/eastgenomics/eggd_RNASeQC/blob/4453d2d3e00616a84adce51b60dc5ed81537934a/dxapp.json#L24)):*
> ```JSON
>         "*.gtf"
>       ],
>       "help": "GTF file containing features to check the bam against. This file should be collapsed so there there are no overlapping transcripts on the same strand and that each gene have a single transcript whose id matches the parent gene id."
> ```

duplicate "there"

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/1)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @Yu-jinKim)

___
*[`dxapp.json` line 24 at r3](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/1#-NR3TX7TAL7jWHK3Lm7c:-NR3UvCCE7IDi8f6ITVK:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_RNASeQC/blob/4453d2d3e00616a84adce51b60dc5ed81537934a/dxapp.json#L24)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

duplicate "there"
</blockquote></details>

Done.

**Review by Yu-jinKim — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_RNASeQC/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Aisha-D)

**Pull request merged**
